export const strings = {
  appTitle: 'Rose Wallet',
  appSubtitle: 'Your cute little money companion',

  // Navigation
  navCozyCorner: 'Cozy Corner',
  navPiggyBank: 'Piggy Bank',
  navGrowBabyGrow: 'Grow Baby Grow',
  navMoneyDiary: 'Money Diary',
  navStashes: 'Stashes',
  navThemes: 'Themes',
  navFinancialStory: 'Financial Story',
  navCustomize: 'Customize',
  sidebarQuickAdd: 'Sprinkle In',

  // Login
  loginWelcome: 'Welcome to Rose Wallet',
  loginSubtitle:
    'Sign in to your cozy corner and keep your money diary up to date.',
  loginEmailLabel: 'E-mail or user name',
  loginEmailPlaceholder: 'Enter your e-mail or user name',
  loginPasswordLabel: 'Password',
  loginPasswordPlaceholder: 'Enter your password',
  loginRememberMe: 'Remember me',
  loginForgotPassword: 'Forgot password?',
  loginButton: 'Login',
  loginWith: 'Log in with',
  loginNoAccount: "Don't have an account?",
  loginSignUp: 'Sign up now',
  loginError: 'Unable to sign in. Please check your credentials.',
  loginSubmitting: 'Signing in...',

  // Register
  registerWelcome: 'Create your Rose Wallet account',
  registerSubtitle: 'Sign up and start filling your money diary.',
  registerFullNameLabel: 'Full name',
  registerFullNamePlaceholder: 'Enter your full name',
  registerPasswordPlaceholder: 'Create a strong password',
  registerConfirmPasswordLabel: 'Confirm password',
  registerConfirmPasswordPlaceholder: 'Re-enter your password',
  registerPasswordHint: 'At least 8 characters with uppercase, lowercase, and a number.',
  registerButton: 'Create account',
  registerSubmitting: 'Creating account...',
  registerHasAccount: 'Already have an account?',
  registerSignIn: 'Sign in',
  registerError: 'Unable to create account. Please try again.',
  registerPasswordMismatch: 'Passwords do not match.',

  // Cozy Corner (Dashboard)
  totalBalance: 'Total Balance',
  savingsRateLabel: 'Savings',
  totalNetWorth: 'Total Net Worth',
  accounts: 'Stashes',
  recentTransactions: 'Recent Money Diary Entries',

  // Stashes (Accounts)
  addAccount: 'Add Stash',
  editAccount: 'Edit Stash',
  archiveAccount: 'Archive Stash',
  accountName: 'Stash Name',
  accountType: 'Stash Type',
  openingBalance: 'Opening Balance',
  currentBalance: 'Current Balance',

  // Account Types
  checking: 'Checking',
  savings: 'Savings',
  cash: 'Cash',
  investment: 'Investment',
  wallet: 'Wallet',

  // Money Diary (Transactions)
  addTransaction: 'Add to Money Diary',
  income: 'Income',
  expense: 'Expense',
  transfer: 'Transfer',
  category: 'Theme',
  amount: 'Amount',
  date: 'Date',
  description: 'Description',
  receipt: 'Receipt Image',

  // Financial Story (Analytics)
  spendingByCategory: 'Spending by Theme',
  expenseCategorization: 'Expense Categorization',
  incomeVsExpense: 'Income vs Expense',
  periodLabel: 'Time period',
  periodMonthly: 'Monthly',
  periodWeekly: 'Weekly',
  periodYearly: 'Yearly',
  periodCustom: 'Custom',
  periodFrom: 'From',
  periodTo: 'To',
  periodMonth: 'Month',
  periodYear: 'Year',
  periodPreviousWeek: 'Previous week',
  periodNextWeek: 'Next week',
  periodCurrentWeek: 'This week',
  allCategories: 'All categories',
  categoriesSelected: 'categories selected',
  noCategoriesSelected: 'No categories selected',
  noExpenseData: 'No data for this period',
  analyticsLoading: 'Loading your financial story...',

  // Piggy Bank (Savings)
  piggyBankCheckup: 'Piggy bank checkup',
  savingsKpiCollected: 'Nest egg so far',
  savingsKpiRemaining: 'Still to stash',
  savingsKpiTargetPool: 'Combined wish list',
  savingsKpiRate: 'How full is the piggy?',
  savingsKpiCollectedLabel: 'Total Collected',
  savingsKpiRemainingLabel: 'Amount to Collect',
  savingsKpiTargetLabel: 'Total Target Pool',
  savingsKpiRateLabel: 'Overall Savings Rate',
  savingsGoalsTitle: 'Savings Goals & Pool Progress',
  savingsAddGoal: 'Add New Goal',
  savingsAddGoalModalTitle: 'New piggy goal',
  savingsGoalNameLabel: 'Goal name',
  savingsGoalNamePlaceholder: 'e.g. Emergency Fund',
  savingsGoalDescriptionLabel: 'Description (optional)',
  savingsGoalDescriptionPlaceholder: 'What is this nest egg for?',
  savingsGoalDateLabel: 'Target date',
  savingsGoalTargetLabel: 'Amount to save',
  savingsGoalRecurringLabel: 'Recurring funds to link',
  savingsGoalRecurringEmpty: 'No recurring funds yet. Create one to start filling this piggy.',
  savingsGoalRecurringCta: 'Create recurring fund',
  savingsGoalsEmpty: 'No piggy goals yet. Add one and link a recurring fund to start tracking.',
  savingsGoalCollected: 'Collected',
  savingsGoalToCollect: 'To Collect',
  savingsGoalTarget: 'Target',
  savingsAnalyticsTitle: 'Analytics & Asset Allocation',
  savingsAssetLocation: 'Where the money naps',
  savingsTrajectoryTitle: 'Savings Trajectory',
  savingsTrajectoryCaption: 'Projected piggy fill date',
  savingsPerMonth: '/mo',
  savingsGoalSubmitting: 'Saving...',
  savingsGoalError: 'Unable to save this goal. Please try again.',

  // Budgets
  budgetLimits: 'Budget Limits',
  setBudget: 'Set Budget',
  remaining: 'Remaining',

  // Unique Features
  finScore: 'Rose Score',
  cashFlowForecast: 'Cash Flow Forecast',
  recurringTransactions: 'Recurring Entries',
  addRecurringPayment: 'Add Recurring Payment',
  frequency: 'Frequency',
  startDate: 'Start Date',
  nextRun: 'Next Run',

  // Common
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  confirm: 'Confirm',
  search: 'Search...',
  filter: 'Filter',
  sort: 'Sort',
  export: 'Export',
  import: 'Import',
};
