export const strings = {
  appTitle: 'Rose Wallet',
  appSubtitle: 'Your cute little money companion',

  // Navigation
  navCozyCorner: 'Cozy Corner',
  navPiggyBank: 'Piggy Bank',
  navGrowBabyGrow: 'Grow Baby Grow',
  navMoneyDiary: 'Money Diary',
  navStashes: 'Stashes',
  navThemes: 'Themes',
  navFinancialStory: 'Financial Story',
  navCustomize: 'Customize',
  sidebarQuickAdd: 'Sprinkle In',

  // Login
  loginWelcome: 'Welcome to Rose Wallet',
  loginSubtitle:
    'Sign in to your cozy corner and keep your money diary up to date.',
  loginEmailLabel: 'E-mail or user name',
  loginEmailPlaceholder: 'Enter your e-mail or user name',
  loginPasswordLabel: 'Password',
  loginPasswordPlaceholder: 'Enter your password',
  loginRememberMe: 'Remember me',
  loginForgotPassword: 'Forgot password?',
  loginButton: 'Login',
  loginWith: 'Log in with',
  loginNoAccount: "Don't have an account?",
  loginSignUp: 'Sign up now',
  loginError: 'Unable to sign in. Please check your credentials.',
  loginSubmitting: 'Signing in...',

  // Register
  registerWelcome: 'Create your Rose Wallet account',
  registerSubtitle: 'Sign up and start filling your money diary.',
  registerFullNameLabel: 'Full name',
  registerFullNamePlaceholder: 'Enter your full name',
  registerPasswordPlaceholder: 'Create a strong password',
  registerConfirmPasswordLabel: 'Confirm password',
  registerConfirmPasswordPlaceholder: 'Re-enter your password',
  registerPasswordHint: 'At least 8 characters with uppercase, lowercase, and a number.',
  registerButton: 'Create account',
  registerSubmitting: 'Creating account...',
  registerHasAccount: 'Already have an account?',
  registerSignIn: 'Sign in',
  registerError: 'Unable to create account. Please try again.',
  registerPasswordMismatch: 'Passwords do not match.',

  // Cozy Corner (Dashboard)
  totalBalance: 'Total Balance',
  savingsRateLabel: 'Savings',
  totalNetWorth: 'Total Net Worth',
  accounts: 'Stashes',
  recentTransactions: 'Recent Money Diary Entries',

  // Stashes (Accounts)
  addAccount: 'Add Stash',
  editAccount: 'Edit Stash',
  archiveAccount: 'Archive Stash',
  accountName: 'Stash Name',
  accountType: 'Stash Type',
  openingBalance: 'Opening Balance',
  currentBalance: 'Current Balance',

  // Account Types
  checking: 'Checking',
  savings: 'Savings',
  cash: 'Cash',
  investment: 'Investment',
  wallet: 'Wallet',

  // Money Diary (Transactions)
  addTransaction: 'Add to Money Diary',
  income: 'Income',
  expense: 'Expense',
  transfer: 'Transfer',
  category: 'Theme',
  amount: 'Amount',
  date: 'Date',
  description: 'Description',
  receipt: 'Receipt Image',

  // Financial Story (Analytics)
  spendingByCategory: 'Spending by Theme',
  expenseCategorization: 'Expense Categorization',
  incomeVsExpense: 'Income vs Expense',
  periodLabel: 'Time period',
  periodMonthly: 'Monthly',
  periodWeekly: 'Weekly',
  periodYearly: 'Yearly',
  periodCustom: 'Custom',
  periodFrom: 'From',
  periodTo: 'To',
  periodMonth: 'Month',
  periodYear: 'Year',
  periodPreviousWeek: 'Previous week',
  periodNextWeek: 'Next week',
  periodCurrentWeek: 'This week',
  allCategories: 'All categories',
  categoriesSelected: 'categories selected',
  noCategoriesSelected: 'No categories selected',
  noExpenseData: 'No data for this period',
  analyticsLoading: 'Loading your financial story...',

  // Budgets
  budgetLimits: 'Budget Limits',
  setBudget: 'Set Budget',
  remaining: 'Remaining',

  // Unique Features
  finScore: 'Rose Score',
  cashFlowForecast: 'Cash Flow Forecast',
  recurringTransactions: 'Recurring Entries',
  addRecurringPayment: 'Add Recurring Payment',
  editRecurringPayment: 'Edit Recurring Payment',
  pauseRecurringPayment: 'Pause',
  resumeRecurringPayment: 'Resume',
  editTransaction: 'Edit Money Diary Entry',
  frequency: 'Frequency',
  startDate: 'Start Date',
  nextRun: 'Next Run',
  paused: 'Paused',
  active: 'Active',

  // Common
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  confirm: 'Confirm',
  search: 'Search...',
  filter: 'Filter',
  sort: 'Sort',
  export: 'Export',
  import: 'Import',
};
